name: evita_ufg_app
description: An app to evaluate UFG teachers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  flutter_native_splash: ^2.2.9
  flutter_slidable: ^2.0.0
  flutter_rating_bar: ^4.0.1
  dio: ^4.0.6
  flutter_form_builder: ^7.7.0
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#0072b9"
  fullscreen: true
  android_12:
    image: assets/images/splash_logo.png
    color: "#0072b9"

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 21