// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCunwSB5vqSV5mOXzSX26HgTnajCv72u8I',
    appId: '1:835688038221:android:d9dd1d89557fc8a7d90104',
    messagingSenderId: '835688038221',
    projectId: 'evita-ufg-4e5ce',
    storageBucket: 'evita-ufg-4e5ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdH-8zHAFDm0YHqyqri1lZIwRdIQabgGU',
    appId: '1:835688038221:ios:c48689beee31f752d90104',
    messagingSenderId: '835688038221',
    projectId: 'evita-ufg-4e5ce',
    storageBucket: 'evita-ufg-4e5ce.appspot.com',
    androidClientId: '835688038221-2ske306fj5i3fji1et3okakiccmmtoqa.apps.googleusercontent.com',
    iosClientId: '835688038221-2l0936ref7cpf1t0b1kvefsrgn8er8q2.apps.googleusercontent.com',
    iosBundleId: 'com.evitaufg.app',
  );
}
