name: Evita App Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build APK
        env:
          API_URL: ${{ secrets.API_URL }}
        run: flutter pub get && flutter clean && flutter build apk --split-per-abi --dart-define API_URL="${API_URL}"
      - name: Release APK
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
